In [1]:
import numpy as np

In [3]:
ex_text = """30373
25512
65332
33549
35390"""

data = ex_text.split("\n")
data = [list(map(int, list(row))) for row in data]
matrix = np.matrix(data)
matrix

matrix([[3, 0, 3, 7, 3],
        [2, 5, 5, 1, 2],
        [6, 5, 3, 3, 2],
        [3, 3, 5, 4, 9],
        [3, 5, 3, 9, 0]])

In [58]:
with open("input.txt") as f:
    data = f.read().split("\n")
data = [list(map(int, list(row))) for row in data]

matrix = np.matrix(data[:-1])
matrix.shape

(99, 99)

In [59]:
def reverse_list(list):
    list.reverse()
    return list


row_shape, column_shape = matrix.shape
# row = 3
# column = 2
# tree_height = matrix[row,column]
scenic_score = []
scenic_score_all = []


for row in range(1,row_shape-1):
    for column in range(1,column_shape-1):
        tree_height = matrix[row,column]

        right = matrix[row,column+1:].tolist()[0]
        left = matrix[row,:column].tolist()[0]
        down = [x[0] for x in matrix[row+1:,column].tolist()]
        up = [x[0] for x in matrix[:row,column].tolist()]

        r_score = 0
        for tree in right:
            if tree < tree_height:
                r_score += 1
            else:
                r_score += 1
                break
        scenic_score.append(r_score)

        d_score = 0
        for tree in down:
            if tree < tree_height:
                d_score += 1
            else:
                d_score += 1
                break
        scenic_score.append(d_score)

        l_score = 0
        for tree in reverse_list(left):
            if tree < tree_height:
                l_score += 1
            else:
                l_score += 1
                break
        scenic_score.append(l_score)

        u_score = 0
        for tree in reverse_list(up):
            if tree < tree_height:
                u_score += 1
            else:
                u_score += 1
                break
        scenic_score.append(u_score)

        scenic_score_total = scenic_score[0]*scenic_score[1]*scenic_score[2]*scenic_score[3]
        scenic_score_all.append(scenic_score_total)
        scenic_score = []
        
max(scenic_score_all)

201600

In [57]:
scenic_score_all

[1, 4, 1, 6, 1, 2, 1, 8, 3]

In [41]:
[x[0] for x in matrix[:row,column].tolist()]

[3]

In [23]:

def reverse_list(list):
    list.reverse()
    return list
reverse_list(right)

[2, 1, 5]

In [14]:
right

matrix([[5, 1, 2]])

In [221]:
row_shape, column_shape = matrix.shape
n_trees_outer = row_shape*2 + column_shape*2 -4

visible_trees = 0

check = []

for row in range(1,row_shape-1):
    for column in range(1,column_shape-1):
        tree_height = matrix[row,column]
        
        right = (tree_height <= matrix[row,column+1:]).sum()
        left = (tree_height <= matrix[row,:column]).sum()
        down = (tree_height <= matrix[row+1:,column]).sum()
        up = (tree_height <= matrix[:row,column]).sum()

        for direction in [right,left,down,up]:
            if direction == 0:
                visible_trees += 1
                check.append((row,column,tree_height))
                break
print(visible_trees + n_trees_outer)        
        
#         visible = (tree_height > matrix[row]).sum() * (tree_height > matrix[:,column]).sum()
#         if visible == 0:
#             visible_trees += 1
#             check.append((row,column,tree_height))



In [222]:
visible_trees + n_trees_outer

1849

In [218]:
matrix

matrix([[3, 0, 3, 7, 3],
        [2, 5, 5, 1, 2],
        [6, 5, 3, 3, 2],
        [3, 3, 5, 4, 9],
        [3, 5, 3, 9, 0]])

In [219]:
check

[(1, 1, 5), (1, 2, 5), (2, 1, 5), (2, 3, 3), (3, 2, 5)]